config/routes.rb
Rails.application.routes.draw do
  resources :users, except: [:destroy]
  namespace :api do
    resources :users, except: [:destroy, :new, :edit]
  end
  root "users#index"
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :user
  validates :zipcode, :state, :city, :street, :neighborhood, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  has_one :address, dependent: :destroy
  accepts_nested_attributes_for :address
  enum status: [User.human_attribute_name(:inactive), User.human_attribute_name(:active)]

  validates :phone, :birthday_at, presence: true
  validates :name, presence: true, fullname: true
  validates_date :birthday_at
  validates :document, presence: true, cpf: true
  validates :email, presence: true, email: true

  has_one_attached :photo

  validates :photo, file_content_type: { allow: ['image/jpeg', 'image/png'] }

  # TODO: refact delivery sms method
  after_create :deliver_welcome_mail#, :deliver_welcome_sms

  def deliver_welcome_mail
    UserMailer.welcome(self).deliver_now
  end

  def deliver_welcome_sms
    require 'net/http'
    url_address = "http://cloud.fowiz.com/api?username=#{ENV['FOWIZ_USERNAME']}&phonenumber=#{self.phone}&message=#{I18n.t('user_sms.welcome.message', user_name: self.name)}&passcode=#{ENV['FOWIZ_PASSWORD']}"

    url = URI.parse(url_address)
    begin
      req = Net::HTTP::Get.new(url.path)
      req = Net::HTTP.start(url.host, url.port) {|http|http.request(req)}
      logger.info "SMS SENDED: #{req.body}"
      true
    rescue => exception
      logger.info exception.message
      return false
    end
  end
end

app/controllers/api/application_controller.rb
class Api::ApplicationController < ActionController::API
  include Response
  include ExceptionHandler
end

app/controllers/api/users_controller.rb
class Api::UsersController < Api::ApplicationController
  include CommonToUsers
  before_action :set_users, only: :index
  before_action :set_user, only: [:show, :update]

  def index
    if stale?(last_modified: @users.last.updated_at)
      json_response(@users.to_json(include: :address))
    end
  end

  def create
    @user = User.create!(user_params)
    json_response(user_json_with_address, :created)
  end

  def show
    if stale?(last_modified: @user.updated_at)
      json_response(user_json_with_address)
    end
  end

  def update
    @user.update!(user_params)
    json_response(user_json_with_address)
  end

  private
    def user_json_with_address
      @user.to_json(include: :address)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/concerns/common_to_users.rb
module CommonToUsers
  extend ActiveSupport::Concern

  included do
    def set_users
      @users ||= get_users
    end

    def get_users
      User.order(created_at: :desc)
    end

    def set_user
      @user = User.find(params[:id])
    end

    def only_if_exists
      redirect_to users_path unless @user.present?
    end

    def user_params
      params.require(:user).permit(
        :name, :document, :email, :birthday_at, :phone, :active, :photo,
        address_attributes: [:id, :zipcode, :state, :city, :street, :neighborhood, :complement, :ibge_code]
      )
    end
  end
end

app/controllers/concerns/exception_handler.rb
module ExceptionHandler
  extend ActiveSupport::Concern

  included do
    rescue_from ActiveRecord::RecordNotFound do |e|
      json_response({ message: e.message }, :not_found)
    end

    rescue_from ActiveRecord::RecordInvalid do |e|
      json_response({ message: e.message }, :unprocessable_entity)
    end
  end
end

app/controllers/concerns/response.rb
module Response
  def json_response(object, status = :ok)
    render json: object, status: status
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include CommonToUsers
  # TODO: Search with elastic search
  include CableReady::Broadcaster
  before_action :set_user, :only_if_exists, only: [:edit, :update, :destroy]
  before_action :set_users, only: [:edit,:index]

  # GET /users or /users.json
  def index
    @user = User.new
    @user.build_address
  end

  # GET /users/1/edit
  def edit
    @user.build_address if @user.address.nil?
    render action: :index
  end

  def create
    User.create(user_params)
    dispatch_update_user_list
    redirect_to users_path
  end

  def update
    dispatch_update_user_list if @user.update_attributes(user_params)

    redirect_to users_path
  end
  private
    def dispatch_update_user_list
      cable_ready["users"].insert_adjacent_html(
        selector: "#users",
        position: "afterbegin",
        html: render_to_string(partial: "user", collection: get_users)
      )
      cable_ready.broadcast
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def avatar_image(user)
    if user.nil? || !user.photo.attached?
      asset_url('avatar.jpg')
    else
      url_for(user.photo)
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%=I18n.t('application_name')%></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.16/jquery.mask.min.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  </head>

  <body>
    <div class="container h-100">
      <div class="row mt-4 justify-content-center align-items-center">
        <div class="col-12">
          <h2 id="application_title"><%=I18n.t('application_name')%></h2>
          <%= link_to I18n.t('helpers.submit.create', model: User.model_name.human), root_path, class: 'btn btn-primary' %>
          <hr />
        </div>
      </div>
      <%= yield %>
    </div>
  </body>
  <script>
    $(document).on('ready turbolinks:load', function() {
      $('.phone_with_ddd').mask('(00) 00000-0000');
      $('.cep').mask('00000-000');
      $('.cpf').mask('000.000.000-00', {reverse: true});
    });
  </script>
</html>

app/views/users/_form.html.erb
<%= form_with model: user, local: true do |form| %>
  <div class="card mb-4 pb-4 bg-light">
    <legend class="p-4"><%=I18n.t('user_form_title')%></legend>
    <div class="row">
      <div class="col-md-2 justify-content-center align-items-center text-align-center">
        <%=image_tag avatar_image(user), class: 'avatar' %>
      </div>
      <div class="col-md-10">
        <div class="row">
          <div class="col-md-6">
            <%= form.label :name, class: 'col-sm-4 col-form-label' %>
            <div class="col-sm-8">
              <%= form.text_field :name, class: 'form-control', placeholder: "#{User.human_attribute_name(:name)}...", required: true %>
            </div>
          </div>

          <div class="col-md-6">
            <%= form.label :document, class: 'col-sm-4 col-form-label' %>
            <div class="col-sm-8">
              <%= form.text_field :document, class: 'form-control cpf', placeholder: "#{User.human_attribute_name(:document)}...", required: true %>
            </div>
          </div>
        </div>

        <div class="row">
          <div class="col-md-6">
            <%= form.label :email, class: 'col-sm-4 col-form-label' %>
            <div class="col-sm-8">
              <%= form.email_field :email, class: 'form-control', placeholder: "#{User.human_attribute_name(:email)}...", required: true %>
            </div>
          </div>

          <div class="col-md-6">
            <%= form.label :photo, class: 'col-sm-4 col-form-label' %>
            <div class="col-sm-8">
              <%= form.file_field :photo, class: 'form-control', placeholder: "#{User.human_attribute_name(:photo)}...", required: user.new_record? %>
            </div>
          </div>
        </div>

        <!-- # TODO: Phone and CellPhone Masks -->
        <div class="row">
          <div class="col-md-6">
            <%= form.label :phone, class: 'col-sm-4 col-form-label' %>
            <div class="col-sm-8">
              <%= form.text_field :phone, class: 'form-control phone_with_ddd', placeholder: "#{User.human_attribute_name(:phone)}...", required: true %>
            </div>
          </div>

          <div class="col-md-6">
            <%= form.label :status, class: 'col-sm-4 col-form-label' %>
            <div class="col-sm-8">
              <%= form.select :status, options_for_select({ User.human_attribute_name(:active) => 1, User.human_attribute_name(:inactive) => 0 }), {}, { class: 'form-control' } %>
            </div>
          </div>
        </div>

        <div class="row">
          <div class="col-md-12">
            <%= form.label :birthday_at, class: 'col-sm-6 col-form-label' %>
            <div class="col-sm-6">
              <%= form.date_select :birthday_at, {end_year: Date.today.year, use_short_month: true, order: [:day, :month, :year]}, { class: 'form-control', style: 'width: auto; display: inline' } %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="card mb-4 mt-4 pb-4 bg-light">
    <!-- # TODO: Auto complete with ajax -->
    <legend class="p-4"><%=Address.model_name.human%></legend>
    <%= form.fields_for :address do |form_address| %>
      <div class="row">
        <div class="col-md-6">
          <%= form_address.label :zipcode, class: 'col-sm-4 col-form-label' %>
          <div class="col-sm-8">
            <%= form_address.text_field :zipcode, class: 'form-control cep', placeholder: "#{Address.human_attribute_name(:zipcode)}...", required: true %>
          </div>
        </div>

        <div class="col-md-6">
          <%= form_address.label :ibge_code, class: 'col-sm-4 col-form-label' %>
          <div class="col-sm-8">
            <%= form_address.text_field :ibge_code, class: 'form-control', placeholder: "#{Address.human_attribute_name(:ibge_code)}...", required: true %>
          </div>
        </div>
      </div>

      <div class="row">
        <div class="col-md-6">
          <%= form_address.label :state, class: 'col-sm-4 col-form-label' %>
          <div class="col-sm-8">
            <%= form_address.text_field :state, class: 'form-control', placeholder: "#{Address.human_attribute_name(:state)}...", required: true %>
          </div>
        </div>

        <div class="col-md-6">
          <%= form_address.label :city, class: 'col-sm-4 col-form-label' %>
          <div class="col-sm-8">
            <%= form_address.text_field :city, class: 'form-control', placeholder: "#{Address.human_attribute_name(:city)}...", required: true %>
          </div>
        </div>
      </div>

      <div class="row">
        <div class="col-md-6">
          <%= form_address.label :street, class: 'col-sm-4 col-form-label' %>
          <div class="col-sm-8">
            <%= form_address.text_field :street, class: 'form-control', placeholder: "#{Address.human_attribute_name(:street)}...", required: true %>
          </div>
        </div>

        <div class="col-md-6">
          <%= form_address.label :neighborhood, class: 'col-sm-4 col-form-label' %>
          <div class="col-sm-8">
            <%= form_address.text_field :neighborhood, class: 'form-control', placeholder: "#{Address.human_attribute_name(:neighborhood)}...", required: true %>
          </div>
        </div>
      </div>

      <div class="row">
        <div class="col-md-6">
          <%= form_address.label :complement, class: 'col-sm-4 col-form-label' %>
          <div class="col-sm-8">
            <%= form_address.text_field :complement, class: 'form-control', placeholder: "#{Address.human_attribute_name(:complement)}..." %>
          </div>
        </div>
      </div>
    <% end %>
  </div>

  <div class="row">
    <div class="col-md-12">
      <div class="actions">
        <%= form.submit I18n.t('helpers.submit.submit', model: User.model_name.human), class: "btn btn-primary btn-save" %>
      </div>
    </div>
  </div>


<% end %>

app/views/users/_user.html.erb
<div class="card mb-2 bg-light" id="user-<%= user.id %>">
  <div class="card-body">
    <div class="row">
      <div class="col-md-2">
        <%=image_tag avatar_image(user), class: 'avatar' %>
      </div>
      <div class="col-md-10 user-data">
        <h4 class="card-title text-muted"><%= user.name %> - <%= user.email %></h4>
        <p><%=User.human_attribute_name(:document)%>: <%= user.document %></p>
        <p><%=User.human_attribute_name(:birthday_at)%>: <%= user.birthday_at %></p>
        <p><%=User.human_attribute_name(:phone)%>: <%= user.phone %></p>
        <p><%=User.human_attribute_name(:status)%>: <%= user.status %></p>
        <%= link_to I18n.t('helpers.submit.update', model: User.model_name.human), edit_user_path(user), class: "mt-1 btn btn-secondary btn-sm" %>
      </div>
    </div>

  </div>
</div>

app/views/users/index.html.erb
<%= render partial: 'form', locals: { user: @user } %>
<hr />
<h5><%=I18n.t('user_list_title')%></h5>
<div id="users">
  <%= render partial: 'user', collection: @users %>
</div>